name: Build project (and publish when adequate)

on:
  push:
    branches:
    - stable
    - develop
    paths-ignore:
    - '.**'
  pull_request:
    branches:
    - stable
    - develop
    paths-ignore:
    - '.**'
  workflow_dispatch:
    inputs:
      publish:
        description: 'Run the publish job too'
        required: false
        default: false
        type: boolean

jobs:
  build:
    name: Build for ${{ matrix.targetPlatform }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          #- StandaloneOSX # Build a macOS standalone (Intel 64-bit).
          #- StandaloneWindows # Build a Windows standalone.
          - StandaloneWindows64 # Build a Windows 64-bit standalone.
          - StandaloneLinux64 # Build a Linux 64-bit standalone.
          #- iOS # Build an iOS player.
          - Android # Build an Android .apk standalone app.
          - WebGL # WebGL.
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          #lfs: true
      - uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ matrix.targetPlatform }}
          restore-keys: Library-
      - if: matrix.targetPlatform == 'Android'
        uses: jlumbroso/free-disk-space@v1.3.1
      - uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: ${{ matrix.targetPlatform }}
      - uses: actions/upload-artifact@v4
        with:
          name: Build-${{ matrix.targetPlatform }}
          path: build/${{ matrix.targetPlatform }}

  publish:
    name: Publish to Itch.io (${{ matrix.channel }})
    if: github.event_name == 'push' || (github.event_name == 'workflow_dispatch' && inputs.publish)
    runs-on: ubuntu-latest
    needs: build
    strategy:
      fail-fast: false
      matrix:
        include:
          - channel: windows-${{ github.ref_name }}
            artifact: Build-StandaloneWindows64
          - channel: linux-${{ github.ref_name }}
            artifact: Build-StandaloneLinux64
          - channel: android-${{ github.ref_name }}
            artifact: Build-Android
          - channel: webgl-${{ github.ref_name }}
            artifact: Build-WebGL
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: ${{ matrix.artifact }}
          path: build/${{ matrix.channel }}
      - uses: KikimoraGames/itch-publish@v0.0.3
        with:
          butlerApiKey: ${{ secrets.BUTLER_API_KEY }}
          gameData: build/${{ matrix.channel }}
          itchUsername: naritanara
          itchGameId: the-climb-of-bacty
          buildChannel: ${{ matrix.channel }}
